version: "3.3"
volumes:
  db_storage: {}

services:
    ria:
        build: .
        image: ria_dev:latest
        ports:
            - "127.0.0.1:6000:3000"
        volumes:
            - ./:/app
            - /app/node_modules
        depends_on:
            - database
        environment:
            - DATABASE_HOST=$DATABASE_HOST
            - DATABASE_USER=$DATABASE_USER
            - DATABASE_PASSWORD=$DATABASE_PASSWORD
            - DATABASE_NAME=$DATABASE_NAME
            - DATABASE_DIALECT=$DATABASE_DIALECT
    database:
        image: mysql:8
        ports:
            - '127.0.0.1:2306:3306'
        expose: 
            - '3306'
        volumes:
            - db_storage:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD  
            - MYSQL_USER=$DATABASE_USER  
            - MYSQL_PASSWORD=$DATABASE_PASSWORD  
            - MYSQL_DATABASE=$DATABASE_NAME 
