version: "3.3"
services: 
    ria:
        build: .        
        image: ria:dev
        ports: 
            - "6000:3000"
        extra_hosts:
            - "ria.test.gr:127.0.0.1"
        volumes: 
            - ./:/app
            - /app/node_modules
            # - .:/code
        environment: 
            - PORT=3000
        
