version: "3.3"
volumes:
  db_storage: {}

services:
    ria:
        build:
            context: ./
            dockerfile: Dockerfile
        image: ria_dev:latest
        container_name: ria_dev
        ports:
            - "127.0.0.1:6000:3000"
        volumes:
            - ./:/app
            - /app/node_modules
        depends_on:
            - database
        command: ["./etc/assets/wait-for-it.sh", "database:3306", "--", "npm", "start"]
        environment:
            - DEBUG=$DEBUG
            - SECRET=$SECRET
            - DATABASE_PORT=$DATABASE_PORT
            - DATABASE_HOST=$DATABASE_HOST
            - DATABASE_USER=$DATABASE_USER
            - DATABASE_PASSWORD=$DATABASE_PASSWORD
            - DATABASE_NAME=$DATABASE_NAME
            - DATABASE_DIALECT=$DATABASE_DIALECT
            - SITE=$SITE
            - GSIS_SITE=$GSIS_SITE
            - CLIENT_ID_GOV=$CLIENT_ID_GOV
            - CLIENT_SECRET_GOV=$CLIENT_SECRET_GOV
    database:
        image: mysql:8
        ports:
            - '127.0.0.1:2307:3306'
        expose:
            - '3306'
        container_name: ria_db_dev
        volumes:
            - db_storage:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d
            - ./etc/assets/custom.cnf:/etc/mysql/conf.d/custom.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_USER=$DATABASE_USER
            - MYSQL_PASSWORD=$DATABASE_PASSWORD
            - MYSQL_DATABASE=$DATABASE_NAME

