const routes = require('express').Router()
let database = require("../services/database")
let multer = require('multer');
let upload =  multer({ dest: './uploads/'});

routes.get('/:analysis', function(req,res,next){
    console.log(req.params.analysis)
    res.render("create", {analysis:req.params.analysis})
});

routes.post('/', async function(req,res,next){
    //req.body.author_id="1";
    
    //console.log(req.file)
    
    //groupings for field9
    
    //dimosia_asfaleia_table
    let drastes_adikimata = JSON.stringify([ {"drastes_adikimata_year1": req.body.drastes_adikimata_year1}, {"drastes_adikimata_year2": req.body.drastes_adikimata_year2}, {"drastes_adikimata_year3": req.body.drastes_adikimata_year3}, {"drastes_adikimata_year4": req.body.drastes_adikimata_year4}, {"drastes_adikimata_year5": req.body.drastes_adikimata_year5}, {"drastes_adikimata_prosfata_stoixeia": req.body.drastes_adikimata_prosfata_stoixeia}, {"drastes_adikimata_epidiwkomenos_stoxos": req.body.drastes_adikimata_epidiwkomenos_stoxos}])
    let adikimata_poinikoy_kwdika = JSON.stringify([ {"adikimata_poinikoy_kwdika_year1": req.body.adikimata_poinikoy_kwdika_year1}, {"adikimata_poinikoy_kwdika_year2": req.body.adikimata_poinikoy_kwdika_year2}, {"adikimata_poinikoy_kwdika_year3": req.body.adikimata_poinikoy_kwdika_year3}, {"adikimata_poinikoy_kwdika_year4": req.body.adikimata_poinikoy_kwdika_year4}, {"adikimata_poinikoy_kwdika_year5": req.body.adikimata_poinikoy_kwdika_year5}, {"adikimata_poinikoy_kwdika_prosfata_stoixeia": req.body.adikimata_poinikoy_kwdika_prosfata_stoixeia}, {"adikimata_poinikoy_kwdika_epidiwkomenos_stoxos": req.body.adikimata_poinikoy_kwdika_epidiwkomenos_stoxos}])
    let diapraxthenta_adikimata = JSON.stringify([ {"diapraxthenta_adikimata_year1": req.body.diapraxthenta_adikimata_year1}, {"diapraxthenta_adikimata_year2": req.body.diapraxthenta_adikimata_year2}, {"diapraxthenta_adikimata_year3": req.body.diapraxthenta_adikimata_year3}, {"diapraxthenta_adikimata_year4": req.body.diapraxthenta_adikimata_year4}, {"diapraxthenta_adikimata_year5": req.body.diapraxthenta_adikimata_year5}, {"diapraxthenta_adikimata_prosfata_stoixeia": req.body.diapraxthenta_adikimata_prosfata_stoixeia}, {"diapraxthenta_adikimata_epidiwkomenos_stoxos": req.body.diapraxthenta_adikimata_epidiwkomenos_stoxos}])
    let etisia_statistika = JSON.stringify([ {"etisia_statistika_year1": req.body.etisia_statistika_year1}, {"etisia_statistika_year2": req.body.etisia_statistika_year2}, {"etisia_statistika_year3": req.body.etisia_statistika_year3}, {"etisia_statistika_year4": req.body.etisia_statistika_year4}, {"etisia_statistika_year5": req.body.etisia_statistika_year5}, {"etisia_statistika_prosfata_stoixeia": req.body.etisia_statistika_prosfata_stoixeia}, {"etisia_statistika_epidiwkomenos_stoxos": req.body.etisia_statistika_epidiwkomenos_stoxos}])
    let adikimata_paranomi_eisodos = JSON.stringify([ {"adikimata_paranomi_eisodos_year1": req.body.adikimata_paranomi_eisodos_year1}, {"adikimata_paranomi_eisodos_year2": req.body.adikimata_paranomi_eisodos_year2}, {"adikimata_paranomi_eisodos_year3": req.body.adikimata_paranomi_eisodos_year3}, {"adikimata_paranomi_eisodos_year4": req.body.adikimata_paranomi_eisodos_year4}, {"adikimata_paranomi_eisodos_year5": req.body.adikimata_paranomi_eisodos_year5}, {"adikimata_paranomi_eisodos_prosfata_stoixeia": req.body.adikimata_paranomi_eisodos_prosfata_stoixeia}, {"adikimata_paranomi_eisodos_epidiwkomenos_stoxos": req.body.adikimata_paranomi_eisodos_epidiwkomenos_stoxos}])
    let syxnotita_egklimatwn = JSON.stringify([ {"syxnotita_egklimatwn_year1": req.body.syxnotita_egklimatwn_year1}, {"syxnotita_egklimatwn_year2": req.body.syxnotita_egklimatwn_year2}, {"syxnotita_egklimatwn_year3": req.body.syxnotita_egklimatwn_year3}, {"syxnotita_egklimatwn_year4": req.body.syxnotita_egklimatwn_year4}, {"syxnotita_egklimatwn_year5": req.body.syxnotita_egklimatwn_year5}, {"syxnotita_egklimatwn_prosfata_stoixeia": req.body.syxnotita_egklimatwn_prosfata_stoixeia}, {"syxnotita_egklimatwn_epidiwkomenos_stoxos": req.body.syxnotita_egklimatwn_epidiwkomenos_stoxos}])
    let eksixniasmena_egklimata = JSON.stringify([ {"eksixniasmena_egklimata_year1": req.body.eksixniasmena_egklimata_year1}, {"eksixniasmena_egklimata_year2": req.body.eksixniasmena_egklimata_year2}, {"eksixniasmena_egklimata_year3": req.body.eksixniasmena_egklimata_year3}, {"eksixniasmena_egklimata_year4": req.body.eksixniasmena_egklimata_year4}, {"eksixniasmena_egklimata_year5": req.body.eksixniasmena_egklimata_year5}, {"eksixniasmena_egklimata_prosfata_stoixeia": req.body.eksixniasmena_egklimata_prosfata_stoixeia}, {"eksixniasmena_egklimata_epidiwkomenos_stoxos": req.body.eksixniasmena_egklimata_epidiwkomenos_stoxos}])
    let ergazomenoi_asfaleia = JSON.stringify([ {"ergazomenoi_asfaleia_year1": req.body.ergazomenoi_asfaleia_year1}, {"ergazomenoi_asfaleia_year2": req.body.ergazomenoi_asfaleia_year2}, {"ergazomenoi_asfaleia_year3": req.body.ergazomenoi_asfaleia_year3}, {"ergazomenoi_asfaleia_year4": req.body.ergazomenoi_asfaleia_year4}, {"ergazomenoi_asfaleia_year5": req.body.ergazomenoi_asfaleia_year5}, {"ergazomenoi_asfaleia_prosfata_stoixeia": req.body.ergazomenoi_asfaleia_prosfata_stoixeia}, {"ergazomenoi_asfaleia_epidiwkomenos_stoxos": req.body.ergazomenoi_asfaleia_epidiwkomenos_stoxos}])
    let katoikoi_ana_astynomiko = JSON.stringify([ {"katoikoi_ana_astynomiko_year1": req.body.katoikoi_ana_astynomiko_year1}, {"katoikoi_ana_astynomiko_year2": req.body.katoikoi_ana_astynomiko_year2}, {"katoikoi_ana_astynomiko_year3": req.body.katoikoi_ana_astynomiko_year3}, {"katoikoi_ana_astynomiko_year4": req.body.katoikoi_ana_astynomiko_year4}, {"katoikoi_ana_astynomiko_year5": req.body.katoikoi_ana_astynomiko_year5}, {"katoikoi_ana_astynomiko_prosfata_stoixeia": req.body.katoikoi_ana_astynomiko_prosfata_stoixeia}, {"katoikoi_ana_astynomiko_epidiwkomenos_stoxos": req.body.katoikoi_ana_astynomiko_epidiwkomenos_stoxos}])
    let analogia_astynomikwn_ana_1000_katoikoys = JSON.stringify([ {"analogia_astynomikwn_ana_1000_katoikoys_year1": req.body.analogia_astynomikwn_ana_1000_katoikoys_year1}, {"analogia_astynomikwn_ana_1000_katoikoys_year2": req.body.analogia_astynomikwn_ana_1000_katoikoys_year2}, {"analogia_astynomikwn_ana_1000_katoikoys_year3": req.body.analogia_astynomikwn_ana_1000_katoikoys_year3}, {"analogia_astynomikwn_ana_1000_katoikoys_year4": req.body.analogia_astynomikwn_ana_1000_katoikoys_year4}, {"analogia_astynomikwn_ana_1000_katoikoys_year5": req.body.analogia_astynomikwn_ana_1000_katoikoys_year5}, {"analogia_astynomikwn_ana_1000_katoikoys_prosfata_stoixeia": req.body.analogia_astynomikwn_ana_1000_katoikoys_prosfata_stoixeia}, {"analogia_astynomikwn_ana_1000_katoikoys_epidiwkomenos_stoxos": req.body.analogia_astynomikwn_ana_1000_katoikoys_epidiwkomenos_stoxos}])
    let dapanes_astynomias = JSON.stringify([ {"dapanes_astynomias_year1": req.body.dapanes_astynomias_year1}, {"dapanes_astynomias_year2": req.body.dapanes_astynomias_year2}, {"dapanes_astynomias_year": req.body.dapanes_astynomias_year3}, {"dapanes_astynomias_year4": req.body.dapanes_astynomias_year4}, {"dapanes_astynomias_year5": req.body.dapanes_astynomias_year5}, {"dapanes_astynomias_prosfata_stoixeia": req.body.dapanes_astynomias_prosfata_stoixeia}, {"dapanes_astynomias_epidiwkomenos_stoxos": req.body.dapanes_astynomias_epidiwkomenos_stoxos}])
    let poroi_antimetwpisis = JSON.stringify([ {"poroi_antimetwpisis_year1": req.body.poroi_antimetwpisis_year1}, {"poroi_antimetwpisis_year2": req.body.poroi_antimetwpisis_year2}, {"poroi_antimetwpisis_year3": req.body.poroi_antimetwpisis_year3}, {"poroi_antimetwpisis_year4": req.body.poroi_antimetwpisis_year4}, {"poroi_antimetwpisis_year5": req.body.poroi_antimetwpisis_year5}, {"poroi_antimetwpisis_prosfata_stoixeia": req.body.poroi_antimetwpisis_prosfata_stoixeia}, {"poroi_antimetwpisis_epidiwkomenos_stoxos": req.body.poroi_antimetwpisis_epidiwkomenos_stoxos}])

    //dikaiosini_table
    let arithmos_diaforwn = JSON.stringify([ {"arithmos_diaforwn_year1": req.body.arithmos_diaforwn_year1}, {"arithmos_diaforwn_year2": req.body.arithmos_diaforwn_year2}, {"arithmos_diaforwn_year3": req.body.arithmos_diaforwn_year3}, {"arithmos_diaforwn_year4": req.body.arithmos_diaforwn_year4}, {"arithmos_diaforwn_year5": req.body.arithmos_diaforwn_year5}, {"arithmos_diaforwn_prosfata_stoixeia": req.body.arithmos_diaforwn_prosfata_stoixeia}, {"arithmos_diaforwn_epidiwkomenos_stoxos": req.body.arithmos_diaforwn_epidiwkomenos_stoxos}])
    let dioikitikes_periptwseis = JSON.stringify([ {"dioikitikes_periptwseis_year1": req.body.dioikitikes_periptwseis_year1}, {"dioikitikes_periptwseis_year2": req.body.dioikitikes_periptwseis_year2}, {"dioikitikes_periptwseis_year3": req.body.dioikitikes_periptwseis_year3}, {"dioikitikes_periptwseis_year4": req.body.dioikitikes_periptwseis_year4}, {"dioikitikes_periptwseis_year5": req.body.dioikitikes_periptwseis_year5}, {"dioikitikes_periptwseis_prosfata_stoixeia": req.body.dioikitikes_periptwseis_prosfata_stoixeia}, {"dioikitikes_periptwseis_epidiwkomenos_stoxos": req.body.dioikitikes_periptwseis_epidiwkomenos_stoxos}])
    let xronos_epilysis_ypothesewn = JSON.stringify([ {"xronos_epilysis_ypothesewn_year1": req.body.xronos_epilysis_ypothesewn_year1}, {"arithmos_diaforwn_year2": req.body.xronos_epilysis_ypothesewn_year2}, {"xronos_epilysis_ypothesewn_year3": req.body.xronos_epilysis_ypothesewn_year3}, {"xronos_epilysis_ypothesewn_year4": req.body.xronos_epilysis_ypothesewn_year4}, {"xronos_epilysis_ypothesewn_year5": req.body.xronos_epilysis_ypothesewn_year5}, {"xronos_epilysis_ypothesewn_prosfata_stoixeia": req.body.xronos_epilysis_ypothesewn_prosfata_stoixeia}, {"xronos_epilysis_ypothesewn_epidiwkomenos_stoxos": req.body.xronos_epilysis_ypothesewn_epidiwkomenos_stoxos}])
    let ekdosi_apofasewn = JSON.stringify([ {"ekdosi_apofasewn_year1": req.body.ekdosi_apofasewn_year1}, {"ekdosi_apofasewn_year2": req.body.ekdosi_apofasewn_year2}, {"ekdosi_apofasewn_year3": req.body.ekdosi_apofasewn_year3}, {"ekdosi_apofasewn_year4": req.body.ekdosi_apofasewn_year4}, {"ekdosi_apofasewn_year5": req.body.ekdosi_apofasewn_year5}, {"ekdosi_apofasewn_prosfata_stoixeia": req.body.ekdosi_apofasewn_prosfata_stoixeia}, {"mo_ypotheswn_dikasti_prosfata_stoixeia": req.body.mo_ypotheswn_dikasti_prosfata_stoixeia}])
    let mo_ypotheswn_dikasti = JSON.stringify([ {"mo_ypotheswn_dikasti_year1": req.body.mo_ypotheswn_dikasti_year1}, {"mo_ypotheswn_dikasti_year2": req.body.mo_ypotheswn_dikasti_year2}, {"mo_ypotheswn_dikasti_year3": req.body.mo_ypotheswn_dikasti_year3}, {"mo_ypotheswn_dikasti_year4": req.body.mo_ypotheswn_dikasti_year4}, {"mo_ypotheswn_dikasti_year5": req.body.mo_ypotheswn_dikasti_year5}, {"mo_ypotheswn_dikasti_prosfata_stoixeia": req.body.mo_ypotheswn_dikasti_prosfata_stoixeia}, {"mo_ypotheswn_dikasti_epidiwkomenos_stoxos": req.body.mo_ypotheswn_dikasti_epidiwkomenos_stoxos}])
    let akyrwsi_apofasewn = JSON.stringify([ {"akyrwsi_apofasewn_year1": req.body.akyrwsi_apofasewn_year1}, {"akyrwsi_apofasewn_year2": req.body.akyrwsi_apofasewn_year2}, {"akyrwsi_apofasewn_year3": req.body.akyrwsi_apofasewn_year3}, {"akyrwsi_apofasewn_year4": req.body.akyrwsi_apofasewn_year4}, {"akyrwsi_apofasewn_year5": req.body.akyrwsi_apofasewn_year5}, {"akyrwsi_apofasewn_prosfata_stoixeia": req.body.akyrwsi_apofasewn_prosfata_stoixeia}, {"akyrwsi_apofasewn_epidiwkomenos_stoxos": req.body.akyrwsi_apofasewn_epidiwkomenos_stoxos}])
    let ekswdikastikos_symvivasmos = JSON.stringify([ {"ekswdikastikos_symvivasmos_year1": req.body.ekswdikastikos_symvivasmos_year1}, {"ekswdikastikos_symvivasmos_year2": req.body.ekswdikastikos_symvivasmos_year2}, {"ekswdikastikos_symvivasmos_year3": req.body.ekswdikastikos_symvivasmos_year3}, {"ekswdikastikos_symvivasmos_year4": req.body.ekswdikastikos_symvivasmos_year4}, {"ekswdikastikos_symvivasmos_year5": req.body.ekswdikastikos_symvivasmos_year5}, {"ekswdikastikos_symvivasmos_prosfata_stoixeia": req.body.ekswdikastikos_symvivasmos_prosfata_stoixeia}, {"ekswdikastikos_symvivasmos_epidiwkomenos_stoxos": req.body.ekswdikastikos_symvivasmos_epidiwkomenos_stoxos}])
    let enallaktiki_epilysi_diaforwn = JSON.stringify([ {"enallaktiki_epilysi_diaforwn_year1": req.body.enallaktiki_epilysi_diaforwn_year1}, {"enallaktiki_epilysi_diaforwn_year2": req.body.enallaktiki_epilysi_diaforwn_year2}, {"enallaktiki_epilysi_diaforwn_year3": req.body.enallaktiki_epilysi_diaforwn_year3}, {"enallaktiki_epilysi_diaforwn_year4": req.body.enallaktiki_epilysi_diaforwn_year4}, {"enallaktiki_epilysi_diaforwn_year5": req.body.enallaktiki_epilysi_diaforwn_year5}, {"enallaktiki_epilysi_diaforwn_prosfata_stoixeia": req.body.enallaktiki_epilysi_diaforwn_prosfata_stoixeia}, {"enallaktiki_epilysi_diaforwn_epidiwkomenos_stoxos": req.body.enallaktiki_epilysi_diaforwn_epidiwkomenos_stoxos}])
    let nomiki_prostasia = JSON.stringify([ {"nomiki_prostasia_year1": req.body.nomiki_prostasia_year1}, {"nomiki_prostasia_year2": req.body.nomiki_prostasia_year2}, {"nomiki_prostasia_year3": req.body.nomiki_prostasia_year3}, {"nomiki_prostasia_year4": req.body.nomiki_prostasia_year4}, {"nomiki_prostasia_year5": req.body.nomiki_prostasia_year5}, {"nomiki_prostasia_prosfata_stoixeia": req.body.nomiki_prostasia_prosfata_stoixeia}, {"nomiki_prostasia_epidiwkomenos_stoxos": req.body.nomiki_prostasia_epidiwkomenos_stoxos}])
    let kostos_prosfygis = JSON.stringify([ {"kostos_prosfygis_year1": req.body.kostos_prosfygis_year1}, {"kostos_prosfygis_year2": req.body.kostos_prosfygis_year2}, {"kostos_prosfygis_year3": req.body.kostos_prosfygis_year3}, {"kostos_prosfygis_year4": req.body.kostos_prosfygis_year4}, {"kostos_prosfygis_year5": req.body.kostos_prosfygis_year5}, {"kostos_prosfygis_prosfata_stoixeia": req.body.kostos_prosfygis_prosfata_stoixeia}, {"kostos_prosfygis_epidiwkomenos_stoxos": req.body.kostos_prosfygis_epidiwkomenos_stoxos}])
    let ilektroniki_ypovoli_dikografwn = JSON.stringify([ {"ilektroniki_ypovoli_dikografwn_year1": req.body.ilektroniki_ypovoli_dikografwn_year1}, {"ilektroniki_ypovoli_dikografwn_year2": req.body.ilektroniki_ypovoli_dikografwn_year2}, {"ilektroniki_ypovoli_dikografwn_year3": req.body.ilektroniki_ypovoli_dikografwn_year3}, {"ilektroniki_ypovoli_dikografwn_year4": req.body.ilektroniki_ypovoli_dikografwn_year4}, {"ilektroniki_ypovoli_dikografwn_year5": req.body.ilektroniki_ypovoli_dikografwn_year5}, {"ilektroniki_ypovoli_dikografwn_prosfata_stoixeia": req.body.ilektroniki_ypovoli_dikografwn_prosfata_stoixeia}, {"ilektroniki_ypovoli_dikografwn_epidiwkomenos_stoxos": req.body.ilektroniki_ypovoli_dikografwn_epidiwkomenos_stoxos}])
    let diekperaiwsi_ypothesewn = JSON.stringify([ {"diekperaiwsi_ypothesewn_year1": req.body.diekperaiwsi_ypothesewn_year1}, {"diekperaiwsi_ypothesewn_year2": req.body.diekperaiwsi_ypothesewn_year2}, {"diekperaiwsi_ypothesewn_year3": req.body.diekperaiwsi_ypothesewn_year3}, {"diekperaiwsi_ypothesewn_year4": req.body.diekperaiwsi_ypothesewn_year4}, {"diekperaiwsi_ypothesewn_year5": req.body.diekperaiwsi_ypothesewn_year5}, {"diekperaiwsi_ypothesewn_prosfata_stoixeia": req.body.diekperaiwsi_ypothesewn_prosfata_stoixeia}, {"diekperaiwsi_ypothesewn_epidiwkomenos_stoxos": req.body.diekperaiwsi_ypothesewn_epidiwkomenos_stoxos}])
    let poines_se_xrima = JSON.stringify([ {"poines_se_xrima_year1": req.body.poines_se_xrima_year1}, {"poines_se_xrima_year2": req.body.poines_se_xrima_year2}, {"poines_se_xrima_year3": req.body.poines_se_xrima_year3}, {"poines_se_xrima_year4": req.body.poines_se_xrima_year4}, {"poines_se_xrima_year5": req.body.poines_se_xrima_year5}, {"poines_se_xrima_prosfata_stoixeia": req.body.poines_se_xrima_prosfata_stoixeia}, {"poines_se_xrima_epidiwkomenos_stoxos": req.body.poines_se_xrima_epidiwkomenos_stoxos}])
    let kostos_swfronismou = JSON.stringify([ {"kostos_swfronismou_year1": req.body.kostos_swfronismou_year1}, {"kostos_swfronismou_year2": req.body.kostos_swfronismou_year2}, {"kostos_swfronismou_year3": req.body.kostos_swfronismou_year3}, {"kostos_swfronismou_year4": req.body.kostos_swfronismou_year4}, {"kostos_swfronismou_year5": req.body.kostos_swfronismou_year5}, {"kostos_swfronismou_prosfata_stoixeia": req.body.kostos_swfronismou_prosfata_stoixeia}, {"kostos_swfronismou_epidiwkomenos_stoxos": req.body.kostos_swfronismou_epidiwkomenos_stoxos}])
    let analogia_fylakwn_kratoumenwn = JSON.stringify([ {"analogia_fylakwn_kratoumenwn_year1": req.body.analogia_fylakwn_kratoumenwn_year1}, {"analogia_fylakwn_kratoumenwn_year2": req.body.analogia_fylakwn_kratoumenwn_year2}, {"analogia_fylakwn_kratoumenwn_year3": req.body.analogia_fylakwn_kratoumenwn_year3}, {"analogia_fylakwn_kratoumenwn_year4": req.body.analogia_fylakwn_kratoumenwn_year4}, {"analogia_fylakwn_kratoumenwn_year5": req.body.analogia_fylakwn_kratoumenwn_year5}, {"analogia_fylakwn_kratoumenwn_prosfata_stoixeia": req.body.analogia_fylakwn_kratoumenwn_prosfata_stoixeia}, {"analogia_fylakwn_kratoumenwn_epidiwkomenos_stoxos": req.body.analogia_fylakwn_kratoumenwn_epidiwkomenos_stoxos}])

    //ependytiki_drastiriotita_table
    let pagkosmia_antagwnistikotita = JSON.stringify([ {"pagkosmia_antagwnistikotita_year1": req.body.pagkosmia_antagwnistikotita_year1}, {"pagkosmia_antagwnistikotita_year2": req.body.pagkosmia_antagwnistikotita_year2}, {"pagkosmia_antagwnistikotita_year3": req.body.pagkosmia_antagwnistikotita_year3}, {"pagkosmia_antagwnistikotita_year4": req.body.pagkosmia_antagwnistikotita_year4}, {"pagkosmia_antagwnistikotita_year5": req.body.pagkosmia_antagwnistikotita_year5}, {"pagkosmia_antagwnistikotita_prosfata_stoixeia": req.body.pagkosmia_antagwnistikotita_prosfata_stoixeia}, {"pagkosmia_antagwnistikotita_epidiwkomenos_stoxos": req.body.pagkosmia_antagwnistikotita_epidiwkomenos_stoxos}])
    let ependyseis = JSON.stringify([ {"ependyseis_year1": req.body.ependyseis_year1}, {"ependyseis_year2": req.body.ependyseis_year2}, {"ependyseis_year3": req.body.ependyseis_year3}, {"ependyseis_year4": req.body.ependyseis_year4}, {"ependyseis_year5": req.body.ependyseis_year5}, {"ependyseis_prosfata_stoixeia": req.body.ependyseis_prosfata_stoixeia}, {"ependyseis_epidiwkomenos_stoxos": req.body.ependyseis_epidiwkomenos_stoxos}])
    let ameses_ependyseis = JSON.stringify([ {"ameses_ependyseis_year1": req.body.ameses_ependyseis_year1}, {"ameses_ependyseis_year2": req.body.ameses_ependyseis_year2}, {"ameses_ependyseis_year3": req.body.ameses_ependyseis_year3}, {"ameses_ependyseis_year4": req.body.ameses_ependyseis_year4}, {"ameses_ependyseis_year5": req.body.ameses_ependyseis_year5}, {"ameses_ependyseis_prosfata_stoixeia": req.body.ameses_ependyseis_prosfata_stoixeia}, {"ameses_ependyseis_epidiwkomenos_stoxos": req.body.ameses_ependyseis_epidiwkomenos_stoxos}])
    let nees_epixeiriseis = JSON.stringify([ {"nees_epixeiriseis_year1": req.body.nees_epixeiriseis_year1}, {"nees_epixeiriseis_year2": req.body.nees_epixeiriseis_year2}, {"nees_epixeiriseis_year3": req.body.nees_epixeiriseis_year3}, {"nees_epixeiriseis_year4": req.body.nees_epixeiriseis_year4}, {"nees_epixeiriseis_year5": req.body.nees_epixeiriseis_year5}, {"nees_epixeiriseis_prosfata_stoixeia": req.body.nees_epixeiriseis_prosfata_stoixeia}, {"nees_epixeiriseis_epidiwkomenos_stoxos": req.body.nees_epixeiriseis_epidiwkomenos_stoxos}])
    let kleistes_epixeiriseis = JSON.stringify([ {"kleistes_epixeiriseis_year1": req.body.kleistes_epixeiriseis_year1}, {"kleistes_epixeiriseis_year2": req.body.kleistes_epixeiriseis_year2}, {"kleistes_epixeiriseis_year3": req.body.kleistes_epixeiriseis_year3}, {"kleistes_epixeiriseis_year4": req.body.kleistes_epixeiriseis_year4}, {"kleistes_epixeiriseis_year5": req.body.kleistes_epixeiriseis_year5}, {"kleistes_epixeiriseis_prosfata_stoixeia": req.body.kleistes_epixeiriseis_prosfata_stoixeia}, {"kleistes_epixeiriseis_epidiwkomenos_stoxos": req.body.kleistes_epixeiriseis_epidiwkomenos_stoxos}])
    let dioikitiko_kostos = JSON.stringify([ {"dioikitiko_kostos_year1": req.body.dioikitiko_kostos_year1}, {"dioikitiko_kostos_year2": req.body.dioikitiko_kostos_year2}, {"dioikitiko_kostos_year3": req.body.dioikitiko_kostos_year3}, {"dioikitiko_kostos_year4": req.body.dioikitiko_kostos_year4}, {"dioikitiko_kostos_year5": req.body.dioikitiko_kostos_year5}, {"dioikitiko_kostos_prosfata_stoixeia": req.body.dioikitiko_kostos_prosfata_stoixeia}, {"dioikitiko_kostos_epidiwkomenos_stoxos": req.body.dioikitiko_kostos_epidiwkomenos_stoxos}])
    let mx_systasis_epixeirisis = JSON.stringify([ {"mx_systasis_epixeirisis_year1": req.body.mx_systasis_epixeirisis_year1}, {"mx_systasis_epixeirisis_year2": req.body.mx_systasis_epixeirisis_year2}, {"mx_systasis_epixeirisis_year3": req.body.mx_systasis_epixeirisis_year3}, {"mx_systasis_epixeirisis_year4": req.body.mx_systasis_epixeirisis_year4}, {"mx_systasis_epixeirisis_year5": req.body.mx_systasis_epixeirisis_year5}, {"mx_systasis_epixeirisis_prosfata_stoixeia": req.body.mx_systasis_epixeirisis_prosfata_stoixeia}, {"mx_systasis_epixeirisis_epidiwkomenos_stoxos": req.body.mx_systasis_epixeirisis_epidiwkomenos_stoxos}])

    //perivallon_energeia_table
    let atmosfairiki_rypansi = JSON.stringify([ {"atmosfairiki_rypansi_year1": req.body.atmosfairiki_rypansi_year1}, {"atmosfairiki_rypansi_year2": req.body.atmosfairiki_rypansi_year2}, {"atmosfairiki_rypansi_year3": req.body.atmosfairiki_rypansi_year3}, {"atmosfairiki_rypansi_year4": req.body.atmosfairiki_rypansi_year4}, {"atmosfairiki_rypansi_year5": req.body.atmosfairiki_rypansi_year5}, {"atmosfairiki_rypansi_prosfata_stoixeia": req.body.atmosfairiki_rypansi_prosfata_stoixeia}, {"atmosfairiki_rypansi_epidiwkomenos_stoxos": req.body.atmosfairiki_rypansi_epidiwkomenos_stoxos}])
    let viologikoi_katharismoi = JSON.stringify([ {"viologikoi_katharismoi_year1": req.body.viologikoi_katharismoi_year1}, {"viologikoi_katharismoi_year2": req.body.viologikoi_katharismoi_year2}, {"viologikoi_katharismoi_year3": req.body.viologikoi_katharismoi_year3}, {"viologikoi_katharismoi_year4": req.body.viologikoi_katharismoi_year4}, {"viologikoi_katharismoi_year5": req.body.viologikoi_katharismoi_year5}, {"viologikoi_katharismoi_prosfata_stoixeia": req.body.viologikoi_katharismoi_prosfata_stoixeia}, {"viologikoi_katharismoi_epidiwkomenos_stoxos": req.body.viologikoi_katharismoi_epidiwkomenos_stoxos}])
    let katallhles_aktes = JSON.stringify([ {"katallhles_aktes_year1": req.body.katallhles_aktes_year1}, {"katallhles_aktes_year2": req.body.katallhles_aktes_year2}, {"katallhles_aktes_year3": req.body.katallhles_aktes_year3}, {"katallhles_aktes_year4": req.body.katallhles_aktes_year4}, {"katallhles_aktes_year5": req.body.katallhles_aktes_year5}, {"katallhles_aktes_prosfata_stoixeia": req.body.katallhles_aktes_prosfata_stoixeia}, {"katallhles_aktes_epidiwkomenos_stoxos": req.body.katallhles_aktes_epidiwkomenos_stoxos}])
    let katallilotita_diktyoy_ydreysis = JSON.stringify([ {"katallilotita_diktyoy_ydreysis_year1": req.body.katallilotita_diktyoy_ydreysis_year1}, {"katallilotita_diktyoy_ydreysis_year2": req.body.katallilotita_diktyoy_ydreysis_year2}, {"katallilotita_diktyoy_ydreysis_year3": req.body.katallilotita_diktyoy_ydreysis_year3}, {"katallilotita_diktyoy_ydreysis_year4": req.body.katallilotita_diktyoy_ydreysis_year4}, {"katallilotita_diktyoy_ydreysis_year5": req.body.katallilotita_diktyoy_ydreysis_year5}, {"katallilotita_diktyoy_ydreysis_prosfata_stoixeia": req.body.katallilotita_diktyoy_ydreysis_prosfata_stoixeia}, {"katallilotita_diktyoy_ydreysis_epidiwkomenos_stoxos": req.body.katallilotita_diktyoy_ydreysis_epidiwkomenos_stoxos}])
    let xrisi_aporrimmatwn = JSON.stringify([ {"xrisi_aporrimmatwn_year1": req.body.xrisi_aporrimmatwn_year1}, {"xrisi_aporrimmatwn_year2": req.body.xrisi_aporrimmatwn_year2}, {"xrisi_aporrimmatwn_year3": req.body.xrisi_aporrimmatwn_year3}, {"xrisi_aporrimmatwn_year4": req.body.xrisi_aporrimmatwn_year4}, {"xrisi_aporrimmatwn_year5": req.body.xrisi_aporrimmatwn_year5}, {"xrisi_aporrimmatwn_prosfata_stoixeia": req.body.xrisi_aporrimmatwn_prosfata_stoixeia}, {"xrisi_aporrimmatwn_epidiwkomenos_stoxos": req.body.xrisi_aporrimmatwn_epidiwkomenos_stoxos}])
    let aporrimmata_xyta = JSON.stringify([ {"aporrimmata_xyta_year1": req.body.aporrimmata_xyta_year1}, {"aporrimmata_xyta_year2": req.body.aporrimmata_xyta_year2}, {"aporrimmata_xyta_year3": req.body.aporrimmata_xyta_year3}, {"aporrimmata_xyta_year4": req.body.aporrimmata_xyta_year4}, {"aporrimmata_xyta_year5": req.body.aporrimmata_xyta_year5}, {"aporrimmata_xyta_prosfata_stoixeia": req.body.aporrimmata_xyta_prosfata_stoixeia}, {"aporrimmata_xyta_epidiwkomenos_stoxos": req.body.aporrimmata_xyta_epidiwkomenos_stoxos}])
    let katastrofi_dasikwn_ektasewn = JSON.stringify([ {"katastrofi_dasikwn_ektasewn_year1": req.body.katastrofi_dasikwn_ektasewn_year1}, {"katastrofi_dasikwn_ektasewn_year2": req.body.katastrofi_dasikwn_ektasewn_year2}, {"katastrofi_dasikwn_ektasewn_year3": req.body.katastrofi_dasikwn_ektasewn_year3}, {"katastrofi_dasikwn_ektasewn_year4": req.body.katastrofi_dasikwn_ektasewn_year4}, {"katastrofi_dasikwn_ektasewn_year5": req.body.katastrofi_dasikwn_ektasewn_year5}, {"katastrofi_dasikwn_ektasewn_prosfata_stoixeia": req.body.katastrofi_dasikwn_ektasewn_prosfata_stoixeia}, {"katastrofi_dasikwn_ektasewn_epidiwkomenos_stoxos": req.body.katastrofi_dasikwn_ektasewn_epidiwkomenos_stoxos}])
    let anadaswseis = JSON.stringify([ {"anadaswseis_year1": req.body.anadaswseis_year1}, {"anadaswseis_year2": req.body.anadaswseis_year2}, {"anadaswseis_year3": req.body.anadaswseis_year3}, {"anadaswseis_year4": req.body.anadaswseis_year4}, {"anadaswseis_year5": req.body.anadaswseis_year5}, {"anadaswseis_prosfata_stoixeia": req.body.anadaswseis_prosfata_stoixeia}, {"anadaswseis_epidiwkomenos_stoxos": req.body.anadaswseis_epidiwkomenos_stoxos}])
    let prostateuomenes_perioxes = JSON.stringify([ {"prostateuomenes_perioxes_year1": req.body.prostateuomenes_perioxes_year1}, {"prostateuomenes_perioxes_year2": req.body.prostateuomenes_perioxes_year2}, {"prostateuomenes_perioxes_year3": req.body.prostateuomenes_perioxes_year3}, {"prostateuomenes_perioxes_year4": req.body.prostateuomenes_perioxes_year4}, {"prostateuomenes_perioxes_year5": req.body.prostateuomenes_perioxes_year5}, {"prostateuomenes_perioxes_prosfata_stoixeia": req.body.prostateuomenes_perioxes_prosfata_stoixeia}, {"prostateuomenes_perioxes_epidiwkomenos_stoxos": req.body.prostateuomenes_perioxes_epidiwkomenos_stoxos}])
    let proypologismos_prostasias_perivallontos = JSON.stringify([ {"proypologismos_prostasias_perivallontos_year1": req.body.proypologismos_prostasias_perivallontos_year1}, {"proypologismos_prostasias_perivallontos_year2": req.body.proypologismos_prostasias_perivallontos_year2}, {"proypologismos_prostasias_perivallontos_year3": req.body.proypologismos_prostasias_perivallontos_year3}, {"proypologismos_prostasias_perivallontos_year4": req.body.proypologismos_prostasias_perivallontos_year4}, {"proypologismos_prostasias_perivallontos_year5": req.body.proypologismos_prostasias_perivallontos_year5}, {"proypologismos_prostasias_perivallontos_prosfata_stoixeia": req.body.proypologismos_prostasias_perivallontos_prosfata_stoixeia}, {"proypologismos_prostasias_perivallontos_epidiwkomenos_stoxos": req.body.proypologismos_prostasias_perivallontos_epidiwkomenos_stoxos}])
    let katanalwsi_energeias_kata_kefali = JSON.stringify([ {"katanalwsi_energeias_kata_kefali_year1": req.body.katanalwsi_energeias_kata_kefali_year1}, {"katanalwsi_energeias_kata_kefali_year2": req.body.katanalwsi_energeias_kata_kefali_year2}, {"katanalwsi_energeias_kata_kefali_year3": req.body.katanalwsi_energeias_kata_kefali_year3}, {"katanalwsi_energeias_kata_kefali_year4": req.body.katanalwsi_energeias_kata_kefali_year4}, {"katanalwsi_energeias_kata_kefali_year5": req.body.katanalwsi_energeias_kata_kefali_year5}, {"katanalwsi_energeias_kata_kefali_prosfata_stoixeia": req.body.katanalwsi_energeias_kata_kefali_prosfata_stoixeia}, {"katanalwsi_energeias_kata_kefali_epidiwkomenos_stoxos": req.body.katanalwsi_energeias_kata_kefali_epidiwkomenos_stoxos}])
    let katanalwsi_energeias_ana_morfi = JSON.stringify([ {"katanalwsi_energeias_ana_morfi_year1": req.body.katanalwsi_energeias_ana_morfi_year1}, {"katanalwsi_energeias_ana_morfi_year2": req.body.katanalwsi_energeias_ana_morfi_year2}, {"katanalwsi_energeias_ana_morfi_year3": req.body.katanalwsi_energeias_ana_morfi_year3}, {"katanalwsi_energeias_ana_morfi_year4": req.body.katanalwsi_energeias_ana_morfi_year4}, {"katanalwsi_energeias_ana_morfi_year5": req.body.katanalwsi_energeias_ana_morfi_year5}, {"katanalwsi_energeias_ana_morfi_prosfata_stoixeia": req.body.katanalwsi_energeias_ana_morfi_prosfata_stoixeia}, {"katanalwsi_energeias_ana_morfi_epidiwkomenos_stoxos": req.body.katanalwsi_energeias_ana_morfi_epidiwkomenos_stoxos}])
    let katanalwsi_energeias_apo_ananewsimes_piges = JSON.stringify([ {"katanalwsi_energeias_apo_ananewsimes_piges_year1": req.body.katanalwsi_energeias_apo_ananewsimes_piges_year1}, {"katanalwsi_energeias_apo_ananewsimes_piges_year2": req.body.katanalwsi_energeias_apo_ananewsimes_piges_year2}, {"katanalwsi_energeias_apo_ananewsimes_piges_year3": req.body.katanalwsi_energeias_apo_ananewsimes_piges_year3}, {"katanalwsi_energeias_apo_ananewsimes_piges_year4": req.body.katanalwsi_energeias_apo_ananewsimes_piges_year4}, {"katanalwsi_energeias_apo_ananewsimes_piges_year5": req.body.katanalwsi_energeias_apo_ananewsimes_piges_year5}, {"katanalwsi_energeias_apo_ananewsimes_piges_prosfata_stoixeia": req.body.katanalwsi_energeias_apo_ananewsimes_piges_prosfata_stoixeia}, {"katanalwsi_energeias_apo_ananewsimes_piges_epidiwkomenos_stoxos": req.body.katanalwsi_energeias_apo_ananewsimes_piges_epidiwkomenos_stoxos}])
    let meiwsi_ekpompwn_thermokipioy = JSON.stringify([ {"meiwsi_ekpompwn_thermokipioy_year1": req.body.meiwsi_ekpompwn_thermokipioy_year1}, {"meiwsi_ekpompwn_thermokipioy_year2": req.body.meiwsi_ekpompwn_thermokipioy_year2}, {"meiwsi_ekpompwn_thermokipioy_year3": req.body.meiwsi_ekpompwn_thermokipioy_year3}, {"meiwsi_ekpompwn_thermokipioy_year4": req.body.meiwsi_ekpompwn_thermokipioy_year4}, {"meiwsi_ekpompwn_thermokipioy_year5": req.body.meiwsi_ekpompwn_thermokipioy_year5}, {"meiwsi_ekpompwn_thermokipioy_prosfata_stoixeia": req.body.meiwsi_ekpompwn_thermokipioy_prosfata_stoixeia}, {"meiwsi_ekpompwn_thermokipioy_epidiwkomenos_stoxos": req.body.meiwsi_ekpompwn_thermokipioy_epidiwkomenos_stoxos}])



    allos_deiktis1 = JSON.stringify([{"allos_deiktis1": req.body.allos_deiktis1}, {"allos_deiktis1_year1": req.body.allos_deiktis1_year1}, {"allos_deiktis1_year2": req.body.allos_deiktis1_year2}, {"allos_deiktis1_year3": req.body.allos_deiktis1_year3}, {"allos_deiktis1_year4": req.body.allos_deiktis1_year4}, {"allos_deiktis1_year5": req.body.allos_deiktis1_year5}, {"allos_deiktis1_prosfata_stoixeia": req.body.allos_deiktis1_prosfata_stoixeia}, {"allos_deiktis1_epidiwkomenos_stoxos": req.body.allos_deiktis1_epidiwkomenos_stoxos}])
    allos_deiktis2 = JSON.stringify([{"allos_deiktis2": req.body.allos_deiktis2}, {"allos_deiktis2_year1": req.body.allos_deiktis2_year1}, {"allos_deiktis2_year2": req.body.allos_deiktis2_year2}, {"allos_deiktis2_year3": req.body.allos_deiktis2_year3}, {"allos_deiktis2_year4": req.body.allos_deiktis2_year4}, {"allos_deiktis2_year5": req.body.allos_deiktis2_year5}, {"allos_deiktis2_prosfata_stoixeia": req.body.allos_deiktis2_prosfata_stoixeia}, {"allos_deiktis2_epidiwkomenos_stoxos": req.body.allos_deiktis2_epidiwkomenos_stoxos}])
    allos_deiktis3 = JSON.stringify([{"allos_deiktis3": req.body.allos_deiktis3}, {"allos_deiktis3_year1": req.body.allos_deiktis3_year1}, {"allos_deiktis3_year2": req.body.allos_deiktis3_year2}, {"allos_deiktis3_year3": req.body.allos_deiktis3_year3}, {"allos_deiktis3_year4": req.body.allos_deiktis3_year4}, {"allos_deiktis3_year5": req.body.allos_deiktis3_year5}, {"allos_deiktis3_prosfata_stoixeia": req.body.allos_deiktis3_prosfata_stoixeia}, {"allos_deiktis3_epidiwkomenos_stoxos": req.body.allos_deiktis3_epidiwkomenos_stoxos}])
    allos_deiktis4 = JSON.stringify([{"allos_deiktis4": req.body.allos_deiktis4}, {"allos_deiktis4_year1": req.body.allos_deiktis4_year1}, {"allos_deiktis4_year2": req.body.allos_deiktis4_year2}, {"allos_deiktis4_year3": req.body.allos_deiktis4_year3}, {"allos_deiktis4_year4": req.body.allos_deiktis4_year4}, {"allos_deiktis4_year5": req.body.allos_deiktis4_year5}, {"allos_deiktis4_prosfata_stoixeia": req.body.allos_deiktis4_prosfata_stoixeia}, {"allos_deiktis4_epidiwkomenos_stoxos": req.body.allos_deiktis4_epidiwkomenos_stoxos}])
    allos_deiktis5 = JSON.stringify([{"allos_deiktis5": req.body.allos_deiktis5}, {"allos_deiktis5_year1": req.body.allos_deiktis5_year1}, {"allos_deiktis5_year2": req.body.allos_deiktis5_year2}, {"allos_deiktis5_year3": req.body.allos_deiktis5_year3}, {"allos_deiktis5_year4": req.body.allos_deiktis5_year4}, {"allos_deiktis5_year5": req.body.allos_deiktis5_year5}, {"allos_deiktis5_prosfata_stoixeia": req.body.allos_deiktis5_prosfata_stoixeia}, {"allos_deiktis5_epidiwkomenos_stoxos": req.body.allos_deiktis5_epidiwkomenos_stoxos}])
    //console.log("allos_deiktis1: " + allos_deiktis1)


    //grouping each value of each row of table 18 
    let auksisi_esodwn = JSON.stringify([{"field_18_amesa_esoda_thesmoi": req.body.field_18_amesa_esoda_thesmoi}, {"field_18_amesa_esoda_oikonomia": req.body.field_18_amesa_esoda_oikonomia}, {"field_18_amesa_esoda_kinonia": req.body.field_18_amesa_esoda_kinonia}, {"field_18_amesa_esoda_perivallon": req.body.field_18_amesa_esoda_perivallon}, {"field_18_amesa_esoda_nisiwtika": req.body.field_18_amesa_esoda_nisiwtika}])
    let meiwsi_dapanwn = JSON.stringify([{"field_18_amesa_dapanes_thesmoi": req.body.field_18_amesa_dapanes_thesmoi}, {"field_18_amesa_dapanes_oikonomia": req.body.field_18_amesa_dapanes_oikonomia}, {"field_18_amesa_dapanes_kinonia": req.body.field_18_amesa_dapanes_kinonia}, {"field_18_amesa_dapanes_perivallon": req.body.field_18_amesa_dapanes_perivallon}, {"field_18_amesa_dapanes_nisiwtika": req.body.field_18_amesa_dapanes_nisiwtika}])  
    let eksikonomisi_xronou = JSON.stringify([{"field_18_amesa_eksikonomisi_xronou_thesmoi": req.body.field_18_amesa_eksikonomisi_xronou_thesmoi}, {"field_18_amesa_eksikonomisi_xronou_oikonomia": req.body.field_18_amesa_eksikonomisi_xronou_oikonomia}, {"field_18_amesa_eksikonomisi_xronou_kinonia":req.body.field_18_amesa_eksikonomisi_xronou_kinonia}, {"field_18_amesa_eksikonomisi_xronou_perivallon": req.body.field_18_amesa_eksikonomisi_xronou_perivallon}, {"field_18_amesa_eksikonomisi_xronou_nisiwtika": req.body.field_18_amesa_eksikonomisi_xronou_nisiwtika}])
    let apodotikotita = JSON.stringify([{"field_18_amesa_apodotikotita_thesmoi": req.body.field_18_amesa_apodotikotita_thesmoi}, {"field_18_amesa_apodotikotita_oikonomia":req.body.field_18_amesa_apodotikotita_oikonomia}, {"field_18_amesa_apodotikotita_kinonia": req.body.field_18_amesa_apodotikotita_kinonia}, {"field_18_amesa_apodotikotita_perivallon": req.body.field_18_amesa_apodotikotita_perivallon}, {"field_18_amesa_apodotikotita_nisiwtika": req.body.field_18_amesa_apodotikotita_nisiwtika}])
    let amesa_allo = JSON.stringify([{"field_18_amesa_allo_thesmoi": req.body.field_18_amesa_allo_thesmoi}, {"field_18_amesa_allo_oikonomia": req.body.field_18_amesa_allo_oikonomia}, {"field_18_amesa_allo_kinonia": req.body.field_18_amesa_allo_kinonia}, {"field_18_amesa_allo_perivallon": req.body.field_18_amesa_allo_perivallon}, {"field_18_amesa_allo_nisiwtika": req.body.field_18_amesa_allo_nisiwtika}])
    let veltiwsi_ypiresiwn = JSON.stringify([{"field_18_emmesa_veltiosi_thesmoi": req.body.field_18_emmesa_veltiosi_thesmoi}, {"field_18_emmesa_veltiosi_oikonomia": req.body.field_18_emmesa_veltiosi_oikonomia}, {"field_18_emmesa_veltiosi_kinonia": req.body.field_18_emmesa_veltiosi_kinonia}, {"field_18_emmesa_veltiosi_perivallon": req.body.field_18_emmesa_veltiosi_perivallon}, {"field_18_emmesa_veltiosi_nisiwtika": req.body.field_18_emmesa_veltiosi_nisiwtika}])
    let metaxirisi_politwn = JSON.stringify([{"field_18_emmesa_metaxirisi_thesmoi": req.body.field_18_emmesa_metaxirisi_thesmoi}, {"field_18_emmesa_metaxirisi_oikonomia": req.body.field_18_emmesa_metaxirisi_oikonomia}, {"field_18_emmesa_metaxirisi_kinonia": req.body.field_18_emmesa_metaxirisi_kinonia}, {"field_18_emmesa_metaxirisi_perivallon": req.body.field_18_emmesa_metaxirisi_perivallon}, {"field_18_emmesa_metaxirisi_nisiwtika": req.body.field_18_emmesa_metaxirisi_nisiwtika}])
    let diafania_thesmwn = JSON.stringify([{"field_18_emmesa_diafania_thesmoi": req.body.field_18_emmesa_diafania_thesmoi}, {"field_18_emmesa_diafania_oikonomia": req.body.field_18_emmesa_diafania_oikonomia}, {"field_18_emmesa_diafania_kinonia": req.body.field_18_emmesa_diafania_kinonia}, {"field_18_emmesa_diafania_perivallon": req.body.field_18_emmesa_diafania_perivallon}, {"field_18_emmesa_diafania_nisiwtika": req.body.field_18_emmesa_diafania_nisiwtika}])
    let diaxirisi_kindynwn = JSON.stringify([{"field_18_emmesa_diaxirisi_kindinwn_thesmoi": req.body.field_18_emmesa_diaxirisi_kindinwn_thesmoi}, {"field_18_emmesa_diaxirisi_kindinwn_oikonomia": req.body.field_18_emmesa_diaxirisi_kindinwn_oikonomia}, {"field_18_emmesa_diaxirisi_kindinwn_kinonia": req.body.field_18_emmesa_diaxirisi_kindinwn_kinonia}, {"field_18_emmesa_diaxirisi_kindinwn_perivallon": req.body.field_18_emmesa_diaxirisi_kindinwn_perivallon}, {"field_18_emmesa_diaxirisi_kindinwn_nisiwtika": req.body.field_18_emmesa_diaxirisi_kindinwn_nisiwtika}])
    let emmesa_allo = JSON.stringify([{"field_18_emmesa_allo_thesmoi": req.body.field_18_emmesa_allo_thesmoi}, {"field_18_emmesa_allo_oikonomia": req.body.field_18_emmesa_allo_oikonomia}, {"field_18_emmesa_allo_kinonia": req.body.field_18_emmesa_allo_kinonia}, {"field_18_emmesa_allo_perivallon": req.body.field_18_emmesa_allo_perivallon}, {"field_18_emmesa_allo_nisiwtika": req.body.field_18_emmesa_allo_nisiwtika}])

    //grouping table 19 
    let proetimasia = JSON.stringify([{"field_19_efarmogi_proetimasia_thesmoi": req.body.field_19_efarmogi_proetimasia_thesmoi}, {"field_19_efarmogi_proetimasia_oikonomia": req.body.field_19_efarmogi_proetimasia_oikonomia}, {"field_19_efarmogi_proetimasia_kinonia": req.body.field_19_efarmogi_proetimasia_kinonia}, {"field_19_efarmogi_proetimasia_perivallon": req.body.field_19_efarmogi_proetimasia_perivallon}, {"field_19_efarmogi_proetimasia_nisiwtika": req.body.field_19_efarmogi_proetimasia_nisiwtika}])
    let ypodomi = JSON.stringify([{"field_19_efarmogi_ypodomi_thesmoi": req.body.field_19_efarmogi_ypodomi_thesmoi}, {"field_19_efarmogi_ypodomi_oikonomia": req.body.field_19_efarmogi_ypodomi_oikonomia}, {"field_19_efarmogi_ypodomi_kinonia": req.body.field_19_efarmogi_ypodomi_kinonia}, {"field_19_efarmogi_ypodomi_perivallon": req.body.field_19_efarmogi_ypodomi_perivallon}, {"field_19_efarmogi_ypodomi_nisiwtika": req.body.field_19_efarmogi_ypodomi_nisiwtika}])  
    let kinitikotita = JSON.stringify([{"field_19_efarmogi_kinitikotita_thesmoi": req.body.field_19_efarmogi_kinitikotita_thesmoi}, {"field_19_efarmogi_kinitikotita_oikonomia": req.body.field_19_efarmogi_kinitikotita_oikonomia}, {"field_19_efarmogi_kinitikotita_kinonia":req.body.field_19_efarmogi_kinitikotita_kinonia}, {"field_19_efarmogi_kinitikotita_perivallon": req.body.field_19_efarmogi_kinitikotita_perivallon}, {"field_19_efarmogi_kinitikotita_nisiwtika": req.body.field_19_efarmogi_kinitikotita_nisiwtika}])
    let emplekomenoi = JSON.stringify([{"field_19_efarmogi_emplekomenoi_thesmoi": req.body.field_19_efarmogi_emplekomenoi_thesmoi}, {"field_19_efarmogi_emplekomenoi_oikonomia":req.body.field_19_efarmogi_emplekomenoi_oikonomia}, {"field_19_efarmogi_emplekomenoi_kinonia": req.body.field_19_efarmogi_emplekomenoi_kinonia}, {"field_19_efarmogi_emplekomenoi_perivallon": req.body.field_19_efarmogi_emplekomenoi_perivallon}, {"field_19_efarmogi_emplekomenoi_nisiwtika": req.body.field_19_efarmogi_emplekomenoi_nisiwtika}])    
    let efarmogi_allo = JSON.stringify([{"field_19_efarmogi_allo_thesmoi": req.body.field_19_efarmogi_allo_thesmoi}, {"field_19_efarmogi_allo_oikonomia": req.body.field_19_efarmogi_allo_oikonomia}, {"field_19_efarmogi_allo_kinonia": req.body.field_19_efarmogi_allo_kinonia}, {"field_19_efarmogi_allo_perivallon": req.body.field_19_efarmogi_allo_perivallon}, {"field_19_efarmogi_allo_nisiwtika": req.body.field_19_efarmogi_allo_nisiwtika}])
    let apodosi_diaxirisis = JSON.stringify([{"field_19_apodosi_diaxirisis_thesmoi": req.body.field_19_apodosi_diaxirisis_thesmoi}, {"field_19_apodosi_diaxirisis_oikonomia": req.body.field_19_apodosi_diaxirisis_oikonomia}, {"field_19_apodosi_diaxirisis_kinonia": req.body.field_19_apodosi_diaxirisis_kinonia}, {"field_19_apodosi_diaxirisis_perivallon": req.body.field_19_apodosi_diaxirisis_perivallon}, {"field_19_apodosi_diaxirisis_nisiwtika": req.body.field_19_apodosi_diaxirisis_nisiwtika}])
    let ektelesi = JSON.stringify([{"field_19_apodosi_ektelesi_thesmoi": req.body.field_19_apodosi_ektelesi_thesmoi}, {"field_19_apodosi_ektelesi_oikonomia": req.body.field_19_apodosi_ektelesi_oikonomia}, {"field_19_apodosi_ektelesi_kinonia": req.body.field_19_apodosi_ektelesi_kinonia}, {"field_19_apodosi_ektelesi_perivallon": req.body.field_19_apodosi_ektelesi_perivallon}, {"field_19_apodosi_ektelesi_nisiwtika": req.body.field_19_apodosi_ektelesi_nisiwtika}])
    let apodosi_kostos = JSON.stringify([{"field_19_apodosi_kostos_thesmoi": req.body.field_19_apodosi_kostos_thesmoi}, {"field_19_apodosi_kostos_oikonomia": req.body.field_19_apodosi_kostos_oikonomia}, {"field_19_apodosi_kostos_kinonia": req.body.field_19_apodosi_kostos_kinonia}, {"field_19_apodosi_kostos_perivallon": req.body.field_19_apodosi_kostos_perivallon}, {"field_19_apodosi_kostos_nisiwtika": req.body.field_19_apodosi_kostos_nisiwtika}])
    let apodosi_allo = JSON.stringify([{"field_19_apodosi_allo_thesmoi": req.body.field_19_apodosi_allo_thesmoi}, {"field_19_apodosi_allo_oikonomia": req.body.field_19_apodosi_allo_oikonomia}, {"field_19_apodosi_allo_kinonia": req.body.field_19_apodosi_allo_kinonia}, {"field_19_apodosi_allo_perivallon": req.body.field_19_apodosi_allo_perivallon}, {"field_19_apodosi_allo_nisiwtika": req.body.field_19_apodosi_allo_nisiwtika}])

    //------------------------------------------------------------------------------//
    //add row to ekthesi model, map values from req.body & set foreign key equal to session username to get author 
    let res_data = await database.ekthesi.create(req.body);

    let req_body = req.body;//assign req.body to variable
    var keys = Object.keys(req_body);//get keys 
    var field_14_arthro = [];
    var field_14_stoxos = [];
    var value, field_14_temp;
    for (i in keys) {//iterate through keys
       // console.log(i + " " + keys[i])
        if (keys[i].includes("field_14_arthro")) { 
            //console.log("FOUND ROW "+keys[i]);
            value= req_body[keys[i]];//get value from pair
            //console.log(" FOUND val "+value);
            field_14_temp = keys[i];//get key 
            field_14_arthro.push({ field_14_temp: value}); 
        } else if (keys[i].includes("field_14_stoxos")) { 
            value = req_body[keys[i]];
            field_14_temp = keys[i];
            field_14_stoxos.push({ field_14_temp: value}); 
        }
    }    
    //field_14_arthro = JSON.stringify(field_14_arthro);
    //console.log(field_14_arthro);
    //console.log(field_14);
    var author = req.session.username;

    res_data = await database.ekthesi.update({author:author, field_14_arthro:field_14_arthro,field_14_stoxos: field_14_stoxos}, {where:{
        id: res_data.id
    }
    })
    //console.log(res_data)

    //map variables to model's fields
    let rythmiseis_data = await database.rythmiseis.create({auksisi_esodwn: auksisi_esodwn, meiwsi_dapanwn: meiwsi_dapanwn, eksikonomisi_xronou: eksikonomisi_xronou, apodotikotita: apodotikotita, amesa_allo: amesa_allo,
        veltiwsi_ypiresiwn: veltiwsi_ypiresiwn, metaxirisi_politwn: metaxirisi_politwn, diafania_thesmwn: diafania_thesmwn, diaxirisi_kindynwn: diaxirisi_kindynwn, emmesa_allo: emmesa_allo, 
        proetimasia: proetimasia, ypodomi: ypodomi, kinitikotita: kinitikotita, emplekomenoi: emplekomenoi, efarmogi_allo:efarmogi_allo, apodosi_diaxirisis: apodosi_diaxirisis, ektelesi: ektelesi, apodosi_kostos: apodosi_kostos, apodosi_allo: apodosi_allo, rythmisiId: res_data.id } )   

    let field_9_data = await database.field_9.create({
        drastes_adikimata: drastes_adikimata, adikimata_poinikoy_kwdika: adikimata_poinikoy_kwdika, diapraxthenta_adikimata: diapraxthenta_adikimata, etisia_statistika: etisia_statistika, adikimata_paranomi_eisodos: adikimata_paranomi_eisodos, syxnotita_egklimatwn: syxnotita_egklimatwn,  eksixniasmena_egklimata: eksixniasmena_egklimata, ergazomenoi_asfaleia: ergazomenoi_asfaleia, katoikoi_ana_astynomiko: katoikoi_ana_astynomiko, analogia_astynomikwn_ana_1000_katoikoys: analogia_astynomikwn_ana_1000_katoikoys, dapanes_astynomias: dapanes_astynomias, poroi_antimetwpisis: poroi_antimetwpisis,
        arithmos_diaforwn: arithmos_diaforwn, dioikitikes_periptwseis: dioikitikes_periptwseis, xronos_epilysis_ypothesewn: xronos_epilysis_ypothesewn, ekdosi_apofasewn: ekdosi_apofasewn, mo_ypotheswn_dikasti: mo_ypotheswn_dikasti, akyrwsi_apofasewn: akyrwsi_apofasewn, ekswdikastikos_symvivasmos: ekswdikastikos_symvivasmos, enallaktiki_epilysi_diaforwn: enallaktiki_epilysi_diaforwn, nomiki_prostasia: nomiki_prostasia, kostos_prosfygis: kostos_prosfygis, ilektroniki_ypovoli_dikografwn: ilektroniki_ypovoli_dikografwn, diekperaiwsi_ypothesewn: diekperaiwsi_ypothesewn, poines_se_xrima: poines_se_xrima, kostos_swfronismou: kostos_swfronismou, analogia_fylakwn_kratoumenwn: analogia_fylakwn_kratoumenwn,
        pagkosmia_antagwnistikotita: pagkosmia_antagwnistikotita, ependyseis: ependyseis, ameses_ependyseis: ameses_ependyseis, nees_epixeiriseis: nees_epixeiriseis, kleistes_epixeiriseis: kleistes_epixeiriseis, dioikitiko_kostos: dioikitiko_kostos, mx_systasis_epixeirisis: mx_systasis_epixeirisis, 
        atmosfairiki_rypansi: atmosfairiki_rypansi, viologikoi_katharismoi:viologikoi_katharismoi, katallhles_aktes: katallhles_aktes, katallilotita_diktyoy_ydreysis: katallilotita_diktyoy_ydreysis, xrisi_aporrimmatwn: xrisi_aporrimmatwn, aporrimmata_xyta: aporrimmata_xyta, katastrofi_dasikwn_ektasewn: katastrofi_dasikwn_ektasewn, anadaswseis: anadaswseis, prostateuomenes_perioxes:prostateuomenes_perioxes, proypologismos_prostasias_perivallontos: proypologismos_prostasias_perivallontos, katanalwsi_energeias_kata_kefali: katanalwsi_energeias_kata_kefali, katanalwsi_energeias_ana_morfi: katanalwsi_energeias_ana_morfi, katanalwsi_energeias_apo_ananewsimes_piges: katanalwsi_energeias_apo_ananewsimes_piges, meiwsi_ekpompwn_thermokipioy: meiwsi_ekpompwn_thermokipioy,
        allos_deiktis1: allos_deiktis1, allos_deiktis2: allos_deiktis2, allos_deiktis3:allos_deiktis3, allos_deiktis4: allos_deiktis4, allos_deiktis5: allos_deiktis5 , field9Id: res_data.id } )   
        
    res.send(res_data)
});

module.exports = routes;
