const routes = require('express').Router()
const { ekthesi } = require('../services/database');
let database = require("../services/database")
let multer = require('multer');
var upload =  multer({ dest: './uploads/'});

routes.get('/', function(req,res,next){
    res.render("create")
});

routes.post('/', async function(req,res,next){
    req.body.author_id="1";
    
    //console.log(req.file)
    
    //groupings for field9
    var atmosfairiki_rypansi =  JSON.stringify([ {"atmosfairiki_rypansi_year1": req.body.atmosfairiki_rypansi_year1}, {"atmosfairiki_rypansi_year2": req.body.atmosfairiki_rypansi_year2}, {"atmosfairiki_rypansi_year3": req.body.atmosfairiki_rypansi_year3}, {"atmosfairiki_rypansi_year4": req.body.atmosfairiki_rypansi_year4}, {"atmosfairiki_rypansi_year5": req.body.atmosfairiki_rypansi_year5}, {"atmosfairiki_rypansi_prosfata_stoixeia": req.body.atmosfairiki_rypansi_prosfata_stoixeia}, {"atmosfairiki_rypansi_epidiwkomenos_stoxos": req.body.atmosfairiki_rypansi_epidiwkomenos_stoxos}])
    var viologikoi_katharismoi = JSON.stringify([ {"viologikoi_katharismoi_year1": req.body.viologikoi_katharismoi_year1}, {"viologikoi_katharismoi_year2": req.body.viologikoi_katharismoi_year2}, {"viologikoi_katharismoi_year3": req.body.viologikoi_katharismoi_year3}, {"viologikoi_katharismoi_year4": req.body.viologikoi_katharismoi_year4}, {"viologikoi_katharismoi_year5": req.body.viologikoi_katharismoi_year5}, {"viologikoi_katharismoi_prosfata_stoixeia": req.body.viologikoi_katharismoi_prosfata_stoixeia}, {"viologikoi_katharismoi_epidiwkomenos_stoxos": req.body.viologikoi_katharismoi_epidiwkomenos_stoxos}])
    var katallhles_aktes = JSON.stringify([ {"katallhles_aktes_year1": req.body.katallhles_aktes_year1}, {"katallhles_aktes_year2": req.body.katallhles_aktes_year2}, {"katallhles_aktes_year3": req.body.katallhles_aktes_year3}, {"katallhles_aktes_year4": req.body.katallhles_aktes_year4}, {"katallhles_aktes_year5": req.body.katallhles_aktes_year5}, {"katallhles_aktes_prosfata_stoixeia": req.body.katallhles_aktes_prosfata_stoixeia}, {"katallhles_aktes_epidiwkomenos_stoxos": req.body.katallhles_aktes_epidiwkomenos_stoxos}])
    var katallilotita_diktyoy_ydreysis = JSON.stringify([ {"katallilotita_diktyoy_ydreysis_year1": req.body.katallilotita_diktyoy_ydreysis_year1}, {"katallilotita_diktyoy_ydreysis_year2": req.body.katallilotita_diktyoy_ydreysis_year2}, {"katallilotita_diktyoy_ydreysis_year3": req.body.katallilotita_diktyoy_ydreysis_year3}, {"katallilotita_diktyoy_ydreysis_year4": req.body.katallilotita_diktyoy_ydreysis_year4}, {"katallilotita_diktyoy_ydreysis_year5": req.body.katallilotita_diktyoy_ydreysis_year5}, {"katallilotita_diktyoy_ydreysis_prosfata_stoixeia": req.body.katallilotita_diktyoy_ydreysis_prosfata_stoixeia}, {"katallilotita_diktyoy_ydreysis_epidiwkomenos_stoxos": req.body.katallilotita_diktyoy_ydreysis_epidiwkomenos_stoxos}])
    var xrisi_aporrimmatwn = JSON.stringify([ {"xrisi_aporrimmatwn_year1": req.body.xrisi_aporrimmatwn_year1}, {"xrisi_aporrimmatwn_year2": req.body.xrisi_aporrimmatwn_year2}, {"xrisi_aporrimmatwn_year3": req.body.xrisi_aporrimmatwn_year3}, {"xrisi_aporrimmatwn_year4": req.body.xrisi_aporrimmatwn_year4}, {"xrisi_aporrimmatwn_year5": req.body.xrisi_aporrimmatwn_year5}, {"xrisi_aporrimmatwn_prosfata_stoixeia": req.body.xrisi_aporrimmatwn_prosfata_stoixeia}, {"xrisi_aporrimmatwn_epidiwkomenos_stoxos": req.body.xrisi_aporrimmatwn_epidiwkomenos_stoxos}])
    var aporrimmata_xyta = JSON.stringify([ {"aporrimmata_xyta_year1": req.body.aporrimmata_xyta_year1}, {"aporrimmata_xyta_year2": req.body.aporrimmata_xyta_year2}, {"aporrimmata_xyta_year3": req.body.aporrimmata_xyta_year3}, {"aporrimmata_xyta_year4": req.body.aporrimmata_xyta_year4}, {"aporrimmata_xyta_year5": req.body.aporrimmata_xyta_year5}, {"aporrimmata_xyta_prosfata_stoixeia": req.body.aporrimmata_xyta_prosfata_stoixeia}, {"aporrimmata_xyta_epidiwkomenos_stoxos": req.body.aporrimmata_xyta_epidiwkomenos_stoxos}])
    var katastrofi_dasikwn_ektasewn = JSON.stringify([ {"katastrofi_dasikwn_ektasewn_year1": req.body.katastrofi_dasikwn_ektasewn_year1}, {"katastrofi_dasikwn_ektasewn_year2": req.body.katastrofi_dasikwn_ektasewn_year2}, {"katastrofi_dasikwn_ektasewn_year3": req.body.katastrofi_dasikwn_ektasewn_year3}, {"katastrofi_dasikwn_ektasewn_year4": req.body.katastrofi_dasikwn_ektasewn_year4}, {"katastrofi_dasikwn_ektasewn_year5": req.body.katastrofi_dasikwn_ektasewn_year5}, {"katastrofi_dasikwn_ektasewn_prosfata_stoixeia": req.body.katastrofi_dasikwn_ektasewn_prosfata_stoixeia}, {"katastrofi_dasikwn_ektasewn_epidiwkomenos_stoxos": req.body.katastrofi_dasikwn_ektasewn_epidiwkomenos_stoxos}])
    var anadaswseis = JSON.stringify([ {"anadaswseis_year1": req.body.anadaswseis_year1}, {"anadaswseis_year2": req.body.anadaswseis_year2}, {"anadaswseis_year3": req.body.anadaswseis_year3}, {"anadaswseis_year4": req.body.anadaswseis_year4}, {"anadaswseis_year5": req.body.anadaswseis_year5}, {"anadaswseis_prosfata_stoixeia": req.body.anadaswseis_prosfata_stoixeia}, {"anadaswseis_epidiwkomenos_stoxos": req.body.anadaswseis_epidiwkomenos_stoxos}])
    var prostateuomenes_perioxes = JSON.stringify([ {"prostateuomenes_perioxes_year1": req.body.prostateuomenes_perioxes_year1}, {"prostateuomenes_perioxes_year2": req.body.prostateuomenes_perioxes_year2}, {"prostateuomenes_perioxes_year3": req.body.prostateuomenes_perioxes_year3}, {"prostateuomenes_perioxes_year4": req.body.prostateuomenes_perioxes_year4}, {"prostateuomenes_perioxes_year5": req.body.prostateuomenes_perioxes_year5}, {"prostateuomenes_perioxes_prosfata_stoixeia": req.body.prostateuomenes_perioxes_prosfata_stoixeia}, {"prostateuomenes_perioxes_epidiwkomenos_stoxos": req.body.prostateuomenes_perioxes_epidiwkomenos_stoxos}])
    var proypologismos_prostasias_perivallontos = JSON.stringify([ {"proypologismos_prostasias_perivallontos_year1": req.body.proypologismos_prostasias_perivallontos_year1}, {"proypologismos_prostasias_perivallontos_year2": req.body.proypologismos_prostasias_perivallontos_year2}, {"proypologismos_prostasias_perivallontos_year3": req.body.proypologismos_prostasias_perivallontos_year3}, {"proypologismos_prostasias_perivallontos_year4": req.body.proypologismos_prostasias_perivallontos_year4}, {"proypologismos_prostasias_perivallontos_year5": req.body.proypologismos_prostasias_perivallontos_year5}, {"proypologismos_prostasias_perivallontos_prosfata_stoixeia": req.body.proypologismos_prostasias_perivallontos_prosfata_stoixeia}, {"proypologismos_prostasias_perivallontos_epidiwkomenos_stoxos": req.body.proypologismos_prostasias_perivallontos_epidiwkomenos_stoxos}])
    var katanalwsi_energeias_kata_kefali = JSON.stringify([ {"katanalwsi_energeias_kata_kefali_year1": req.body.katanalwsi_energeias_kata_kefali_year1}, {"katanalwsi_energeias_kata_kefali_year2": req.body.katanalwsi_energeias_kata_kefali_year2}, {"katanalwsi_energeias_kata_kefali_year3": req.body.katanalwsi_energeias_kata_kefali_year3}, {"katanalwsi_energeias_kata_kefali_year4": req.body.katanalwsi_energeias_kata_kefali_year4}, {"katanalwsi_energeias_kata_kefali_year5": req.body.katanalwsi_energeias_kata_kefali_year5}, {"katanalwsi_energeias_kata_kefali_prosfata_stoixeia": req.body.katanalwsi_energeias_kata_kefali_prosfata_stoixeia}, {"katanalwsi_energeias_kata_kefali_epidiwkomenos_stoxos": req.body.katanalwsi_energeias_kata_kefali_epidiwkomenos_stoxos}])
    var katanalwsi_energeias_ana_morfi = JSON.stringify([ {"katanalwsi_energeias_ana_morfi_year1": req.body.katanalwsi_energeias_ana_morfi_year1}, {"katanalwsi_energeias_ana_morfi_year2": req.body.katanalwsi_energeias_ana_morfi_year2}, {"katanalwsi_energeias_ana_morfi_year3": req.body.katanalwsi_energeias_ana_morfi_year3}, {"katanalwsi_energeias_ana_morfi_year4": req.body.katanalwsi_energeias_ana_morfi_year4}, {"katanalwsi_energeias_ana_morfi_year5": req.body.katanalwsi_energeias_ana_morfi_year5}, {"katanalwsi_energeias_ana_morfi_prosfata_stoixeia": req.body.katanalwsi_energeias_ana_morfi_prosfata_stoixeia}, {"katanalwsi_energeias_ana_morfi_epidiwkomenos_stoxos": req.body.katanalwsi_energeias_ana_morfi_epidiwkomenos_stoxos}])
    var katanalwsi_energeias_apo_ananewsimes_piges = JSON.stringify([ {"katanalwsi_energeias_apo_ananewsimes_piges_year1": req.body.katanalwsi_energeias_apo_ananewsimes_piges_year1}, {"katanalwsi_energeias_apo_ananewsimes_piges_year2": req.body.katanalwsi_energeias_apo_ananewsimes_piges_year2}, {"katanalwsi_energeias_apo_ananewsimes_piges_year3": req.body.katanalwsi_energeias_apo_ananewsimes_piges_year3}, {"katanalwsi_energeias_apo_ananewsimes_piges_year4": req.body.katanalwsi_energeias_apo_ananewsimes_piges_year4}, {"katanalwsi_energeias_apo_ananewsimes_piges_year5": req.body.katanalwsi_energeias_apo_ananewsimes_piges_year5}, {"katanalwsi_energeias_apo_ananewsimes_piges_prosfata_stoixeia": req.body.katanalwsi_energeias_apo_ananewsimes_piges_prosfata_stoixeia}, {"katanalwsi_energeias_apo_ananewsimes_piges_epidiwkomenos_stoxos": req.body.katanalwsi_energeias_apo_ananewsimes_piges_epidiwkomenos_stoxos}])
    var meiwsi_ekpompwn_thermokipioy = JSON.stringify([ {"meiwsi_ekpompwn_thermokipioy_year1": req.body.meiwsi_ekpompwn_thermokipioy_year1}, {"meiwsi_ekpompwn_thermokipioy_year2": req.body.meiwsi_ekpompwn_thermokipioy_year2}, {"meiwsi_ekpompwn_thermokipioy_year3": req.body.meiwsi_ekpompwn_thermokipioy_year3}, {"meiwsi_ekpompwn_thermokipioy_year4": req.body.meiwsi_ekpompwn_thermokipioy_year4}, {"meiwsi_ekpompwn_thermokipioy_year5": req.body.meiwsi_ekpompwn_thermokipioy_year5}, {"meiwsi_ekpompwn_thermokipioy_prosfata_stoixeia": req.body.meiwsi_ekpompwn_thermokipioy_prosfata_stoixeia}, {"meiwsi_ekpompwn_thermokipioy_epidiwkomenos_stoxos": req.body.meiwsi_ekpompwn_thermokipioy_epidiwkomenos_stoxos}])



    allos_deiktis1 = JSON.stringify([{"allos_deiktis1": req.body.allos_deiktis1}, {"allos_deiktis1_year1": req.body.allos_deiktis1_year1}, {"allos_deiktis1_year2": req.body.allos_deiktis1_year2}, {"allos_deiktis1_year3": req.body.allos_deiktis1_year3}, {"allos_deiktis1_year4": req.body.allos_deiktis1_year4}, {"allos_deiktis1_year5": req.body.allos_deiktis1_year5}, {"allos_deiktis1_prosfata_stoixeia": req.body.allos_deiktis1_prosfata_stoixeia}, {"allos_deiktis1_epidiwkomenos_stoxos": req.body.allos_deiktis1_epidiwkomenos_stoxos}])
    allos_deiktis2 = JSON.stringify([{"allos_deiktis2": req.body.allos_deiktis2}, {"allos_deiktis2_year1": req.body.allos_deiktis2_year1}, {"allos_deiktis2_year2": req.body.allos_deiktis2_year2}, {"allos_deiktis2_year3": req.body.allos_deiktis2_year3}, {"allos_deiktis2_year4": req.body.allos_deiktis2_year4}, {"allos_deiktis2_year5": req.body.allos_deiktis2_year5}, {"allos_deiktis2_prosfata_stoixeia": req.body.allos_deiktis2_prosfata_stoixeia}, {"allos_deiktis2_epidiwkomenos_stoxos": req.body.allos_deiktis2_epidiwkomenos_stoxos}])
    allos_deiktis3 = JSON.stringify([{"allos_deiktis3": req.body.allos_deiktis3}, {"allos_deiktis3_year1": req.body.allos_deiktis3_year1}, {"allos_deiktis3_year2": req.body.allos_deiktis3_year2}, {"allos_deiktis3_year3": req.body.allos_deiktis3_year3}, {"allos_deiktis3_year4": req.body.allos_deiktis3_year4}, {"allos_deiktis3_year5": req.body.allos_deiktis3_year5}, {"allos_deiktis3_prosfata_stoixeia": req.body.allos_deiktis3_prosfata_stoixeia}, {"allos_deiktis3_epidiwkomenos_stoxos": req.body.allos_deiktis3_epidiwkomenos_stoxos}])
    allos_deiktis4 = JSON.stringify([{"allos_deiktis4": req.body.allos_deiktis4}, {"allos_deiktis4_year1": req.body.allos_deiktis4_year1}, {"allos_deiktis4_year2": req.body.allos_deiktis4_year2}, {"allos_deiktis4_year3": req.body.allos_deiktis4_year3}, {"allos_deiktis4_year4": req.body.allos_deiktis4_year4}, {"allos_deiktis4_year5": req.body.allos_deiktis4_year5}, {"allos_deiktis4_prosfata_stoixeia": req.body.allos_deiktis4_prosfata_stoixeia}, {"allos_deiktis4_epidiwkomenos_stoxos": req.body.allos_deiktis4_epidiwkomenos_stoxos}])
    allos_deiktis5 = JSON.stringify([{"allos_deiktis5": req.body.allos_deiktis5}, {"allos_deiktis5_year1": req.body.allos_deiktis5_year1}, {"allos_deiktis5_year2": req.body.allos_deiktis5_year2}, {"allos_deiktis5_year3": req.body.allos_deiktis5_year3}, {"allos_deiktis5_year4": req.body.allos_deiktis5_year4}, {"allos_deiktis5_year5": req.body.allos_deiktis5_year5}, {"allos_deiktis5_prosfata_stoixeia": req.body.allos_deiktis5_prosfata_stoixeia}, {"allos_deiktis5_epidiwkomenos_stoxos": req.body.allos_deiktis5_epidiwkomenos_stoxos}])
    console.log("allos_deiktis1: " + allos_deiktis1)


    //grouping each value of each row of table 18 
    var auksisi_esodwn = JSON.stringify([{"field_18_amesa_esoda_thesmoi": req.body.field_18_amesa_esoda_thesmoi}, {"field_18_amesa_esoda_oikonomia": req.body.field_18_amesa_esoda_oikonomia}, {"field_18_amesa_esoda_kinonia": req.body.field_18_amesa_esoda_kinonia}, {"field_18_amesa_esoda_perivallon": req.body.field_18_amesa_esoda_perivallon}, {"field_18_amesa_esoda_nisiwtika": req.body.field_18_amesa_esoda_nisiwtika}])
    var meiwsi_dapanwn = JSON.stringify([{"field_18_amesa_dapanes_thesmoi": req.body.field_18_amesa_dapanes_thesmoi}, {"field_18_amesa_dapanes_oikonomia": req.body.field_18_amesa_dapanes_oikonomia}, {"field_18_amesa_dapanes_kinonia": req.body.field_18_amesa_dapanes_kinonia}, {"field_18_amesa_dapanes_perivallon": req.body.field_18_amesa_dapanes_perivallon}, {"field_18_amesa_dapanes_nisiwtika": req.body.field_18_amesa_dapanes_nisiwtika}])  
    var eksikonomisi_xronou = JSON.stringify([{"field_18_amesa_eksikonomisi_xronou_thesmoi": req.body.field_18_amesa_eksikonomisi_xronou_thesmoi}, {"field_18_amesa_eksikonomisi_xronou_oikonomia": req.body.field_18_amesa_eksikonomisi_xronou_oikonomia}, {"field_18_amesa_eksikonomisi_xronou_kinonia":req.body.field_18_amesa_eksikonomisi_xronou_kinonia}, {"field_18_amesa_eksikonomisi_xronou_perivallon": req.body.field_18_amesa_eksikonomisi_xronou_perivallon}, {"field_18_amesa_eksikonomisi_xronou_nisiwtika": req.body.field_18_amesa_eksikonomisi_xronou_nisiwtika}])
    var apodotikotita = JSON.stringify([{"field_18_amesa_apodotikotita_thesmoi": req.body.field_18_amesa_apodotikotita_thesmoi}, {"field_18_amesa_apodotikotita_oikonomia":req.body.field_18_amesa_apodotikotita_oikonomia}, {"field_18_amesa_apodotikotita_kinonia": req.body.field_18_amesa_apodotikotita_kinonia}, {"field_18_amesa_apodotikotita_perivallon": req.body.field_18_amesa_apodotikotita_perivallon}, {"field_18_amesa_apodotikotita_nisiwtika": req.body.field_18_amesa_apodotikotita_nisiwtika}])
    var amesa_allo = JSON.stringify([{"field_18_amesa_allo_thesmoi": req.body.field_18_amesa_allo_thesmoi}, {"field_18_amesa_allo_oikonomia": req.body.field_18_amesa_allo_oikonomia}, {"field_18_amesa_allo_kinonia": req.body.field_18_amesa_allo_kinonia}, {"field_18_amesa_allo_perivallon": req.body.field_18_amesa_allo_perivallon}, {"field_18_amesa_allo_nisiwtika": req.body.field_18_amesa_allo_nisiwtika}])
    var veltiwsi_ypiresiwn = JSON.stringify([{"field_18_emmesa_veltiosi_thesmoi": req.body.field_18_emmesa_veltiosi_thesmoi}, {"field_18_emmesa_veltiosi_oikonomia": req.body.field_18_emmesa_veltiosi_oikonomia}, {"field_18_emmesa_veltiosi_kinonia": req.body.field_18_emmesa_veltiosi_kinonia}, {"field_18_emmesa_veltiosi_perivallon": req.body.field_18_emmesa_veltiosi_perivallon}, {"field_18_emmesa_veltiosi_nisiwtika": req.body.field_18_emmesa_veltiosi_nisiwtika}])
    var metaxirisi_politwn = JSON.stringify([{"field_18_emmesa_metaxirisi_thesmoi": req.body.field_18_emmesa_metaxirisi_thesmoi}, {"field_18_emmesa_metaxirisi_oikonomia": req.body.field_18_emmesa_metaxirisi_oikonomia}, {"field_18_emmesa_metaxirisi_kinonia": req.body.field_18_emmesa_metaxirisi_kinonia}, {"field_18_emmesa_metaxirisi_perivallon": req.body.field_18_emmesa_metaxirisi_perivallon}, {"field_18_emmesa_metaxirisi_nisiwtika": req.body.field_18_emmesa_metaxirisi_nisiwtika}])
    var diafania_thesmwn = JSON.stringify([{"field_18_emmesa_diafania_thesmoi": req.body.field_18_emmesa_diafania_thesmoi}, {"field_18_emmesa_diafania_oikonomia": req.body.field_18_emmesa_diafania_oikonomia}, {"field_18_emmesa_diafania_kinonia": req.body.field_18_emmesa_diafania_kinonia}, {"field_18_emmesa_diafania_perivallon": req.body.field_18_emmesa_diafania_perivallon}, {"field_18_emmesa_diafania_nisiwtika": req.body.field_18_emmesa_diafania_nisiwtika}])
    var diaxirisi_kindynwn = JSON.stringify([{"field_18_emmesa_diaxirisi_kindinwn_thesmoi": req.body.field_18_emmesa_diaxirisi_kindinwn_thesmoi}, {"field_18_emmesa_diaxirisi_kindinwn_oikonomia": req.body.field_18_emmesa_diaxirisi_kindinwn_oikonomia}, {"field_18_emmesa_diaxirisi_kindinwn_kinonia": req.body.field_18_emmesa_diaxirisi_kindinwn_kinonia}, {"field_18_emmesa_diaxirisi_kindinwn_perivallon": req.body.field_18_emmesa_diaxirisi_kindinwn_perivallon}, {"field_18_emmesa_diaxirisi_kindinwn_nisiwtika": req.body.field_18_emmesa_diaxirisi_kindinwn_nisiwtika}])
    var emmesa_allo = JSON.stringify([{"field_18_emmesa_allo_thesmoi": req.body.field_18_emmesa_allo_thesmoi}, {"field_18_emmesa_allo_oikonomia": req.body.field_18_emmesa_allo_oikonomia}, {"field_18_emmesa_allo_kinonia": req.body.field_18_emmesa_allo_kinonia}, {"field_18_emmesa_allo_perivallon": req.body.field_18_emmesa_allo_perivallon}, {"field_18_emmesa_allo_nisiwtika": req.body.field_18_emmesa_allo_nisiwtika}])

    //grouping table 19 
    var proetimasia = JSON.stringify([{"field_19_efarmogi_proetimasia_thesmoi": req.body.field_19_efarmogi_proetimasia_thesmoi}, {"field_19_efarmogi_proetimasia_oikonomia": req.body.field_19_efarmogi_proetimasia_oikonomia}, {"field_19_efarmogi_proetimasia_kinonia": req.body.field_19_efarmogi_proetimasia_kinonia}, {"field_19_efarmogi_proetimasia_perivallon": req.body.field_19_efarmogi_proetimasia_perivallon}, {"field_19_efarmogi_proetimasia_nisiwtika": req.body.field_19_efarmogi_proetimasia_nisiwtika}])
    var ypodomi = JSON.stringify([{"field_19_efarmogi_ypodomi_thesmoi": req.body.field_19_efarmogi_ypodomi_thesmoi}, {"field_19_efarmogi_ypodomi_oikonomia": req.body.field_19_efarmogi_ypodomi_oikonomia}, {"field_19_efarmogi_ypodomi_kinonia": req.body.field_19_efarmogi_ypodomi_kinonia}, {"field_19_efarmogi_ypodomi_perivallon": req.body.field_19_efarmogi_ypodomi_perivallon}, {"field_19_efarmogi_ypodomi_nisiwtika": req.body.field_19_efarmogi_ypodomi_nisiwtika}])  
    var kinitikotita = JSON.stringify([{"field_19_efarmogi_kinitikotita_thesmoi": req.body.field_19_efarmogi_kinitikotita_thesmoi}, {"field_19_efarmogi_kinitikotita_oikonomia": req.body.field_19_efarmogi_kinitikotita_oikonomia}, {"field_19_efarmogi_kinitikotita_kinonia":req.body.field_19_efarmogi_kinitikotita_kinonia}, {"field_19_efarmogi_kinitikotita_perivallon": req.body.field_19_efarmogi_kinitikotita_perivallon}, {"field_19_efarmogi_kinitikotita_nisiwtika": req.body.field_19_efarmogi_kinitikotita_nisiwtika}])
    var emplekomenoi = JSON.stringify([{"field_19_efarmogi_emplekomenoi_thesmoi": req.body.field_19_efarmogi_emplekomenoi_thesmoi}, {"field_19_efarmogi_emplekomenoi_oikonomia":req.body.field_19_efarmogi_emplekomenoi_oikonomia}, {"field_19_efarmogi_emplekomenoi_kinonia": req.body.field_19_efarmogi_emplekomenoi_kinonia}, {"field_19_efarmogi_emplekomenoi_perivallon": req.body.field_19_efarmogi_emplekomenoi_perivallon}, {"field_19_efarmogi_emplekomenoi_nisiwtika": req.body.field_19_efarmogi_emplekomenoi_nisiwtika}])    
    var efarmogi_allo = JSON.stringify([{"field_19_efarmogi_allo_thesmoi": req.body.field_19_efarmogi_allo_thesmoi}, {"field_19_efarmogi_allo_oikonomia": req.body.field_19_efarmogi_allo_oikonomia}, {"field_19_efarmogi_allo_kinonia": req.body.field_19_efarmogi_allo_kinonia}, {"field_19_efarmogi_allo_perivallon": req.body.field_19_efarmogi_allo_perivallon}, {"field_19_efarmogi_allo_nisiwtika": req.body.field_19_efarmogi_allo_nisiwtika}])
    var apodosi_diaxirisis = JSON.stringify([{"field_19_apodosi_diaxirisis_thesmoi": req.body.field_19_apodosi_diaxirisis_thesmoi}, {"field_19_apodosi_diaxirisis_oikonomia": req.body.field_19_apodosi_diaxirisis_oikonomia}, {"field_19_apodosi_diaxirisis_kinonia": req.body.field_19_apodosi_diaxirisis_kinonia}, {"field_19_apodosi_diaxirisis_perivallon": req.body.field_19_apodosi_diaxirisis_perivallon}, {"field_19_apodosi_diaxirisis_nisiwtika": req.body.field_19_apodosi_diaxirisis_nisiwtika}])
    var ektelesi = JSON.stringify([{"field_19_apodosi_ektelesi_thesmoi": req.body.field_19_apodosi_ektelesi_thesmoi}, {"field_19_apodosi_ektelesi_oikonomia": req.body.field_19_apodosi_ektelesi_oikonomia}, {"field_19_apodosi_ektelesi_kinonia": req.body.field_19_apodosi_ektelesi_kinonia}, {"field_19_apodosi_ektelesi_perivallon": req.body.field_19_apodosi_ektelesi_perivallon}, {"field_19_apodosi_ektelesi_nisiwtika": req.body.field_19_apodosi_ektelesi_nisiwtika}])
    var apodosi_kostos = JSON.stringify([{"field_19_apodosi_kostos_thesmoi": req.body.field_19_apodosi_kostos_thesmoi}, {"field_19_apodosi_kostos_oikonomia": req.body.field_19_apodosi_kostos_oikonomia}, {"field_19_apodosi_kostos_kinonia": req.body.field_19_apodosi_kostos_kinonia}, {"field_19_apodosi_kostos_perivallon": req.body.field_19_apodosi_kostos_perivallon}, {"field_19_apodosi_kostos_nisiwtika": req.body.field_19_apodosi_kostos_nisiwtika}])
    var apodosi_allo = JSON.stringify([{"field_19_apodosi_allo_thesmoi": req.body.field_19_apodosi_allo_thesmoi}, {"field_19_apodosi_allo_oikonomia": req.body.field_19_apodosi_allo_oikonomia}, {"field_19_apodosi_allo_kinonia": req.body.field_19_apodosi_allo_kinonia}, {"field_19_apodosi_allo_perivallon": req.body.field_19_apodosi_allo_perivallon}, {"field_19_apodosi_allo_nisiwtika": req.body.field_19_apodosi_allo_nisiwtika}])

    //------------------------------------------------------------------------------//
    //add row to ekthesi model, map values from req.body
    let res_data = await ekthesi.create(req.body)
       
    //map variables to model's fields
    let rythmiseis_data = await database.rythmiseis.create({auksisi_esodwn: auksisi_esodwn, meiwsi_dapanwn: meiwsi_dapanwn, eksikonomisi_xronou: eksikonomisi_xronou, apodotikotita: apodotikotita, amesa_allo: amesa_allo,
        veltiwsi_ypiresiwn: veltiwsi_ypiresiwn, metaxirisi_politwn: metaxirisi_politwn, diafania_thesmwn: diafania_thesmwn, diaxirisi_kindynwn: diaxirisi_kindynwn, emmesa_allo: emmesa_allo, 
        proetimasia: proetimasia, ypodomi: ypodomi, kinitikotita: kinitikotita, emplekomenoi: emplekomenoi, efarmogi_allo:efarmogi_allo, apodosi_diaxirisis: apodosi_diaxirisis, ektelesi: ektelesi, apodosi_kostos: apodosi_kostos, apodosi_allo: apodosi_allo, rythmisiId: res_data.id } )   

    let field_9_data = await database.field_9.create({ atmosfairiki_rypansi: atmosfairiki_rypansi, viologikoi_katharismoi:viologikoi_katharismoi, katallhles_aktes: katallhles_aktes, katallilotita_diktyoy_ydreysis: katallilotita_diktyoy_ydreysis, xrisi_aporrimmatwn: xrisi_aporrimmatwn, aporrimmata_xyta: aporrimmata_xyta, katastrofi_dasikwn_ektasewn: katastrofi_dasikwn_ektasewn, anadaswseis: anadaswseis, prostateuomenes_perioxes:prostateuomenes_perioxes, proypologismos_prostasias_perivallontos: proypologismos_prostasias_perivallontos, katanalwsi_energeias_kata_kefali: katanalwsi_energeias_kata_kefali, katanalwsi_energeias_ana_morfi: katanalwsi_energeias_ana_morfi, katanalwsi_energeias_apo_ananewsimes_piges: katanalwsi_energeias_apo_ananewsimes_piges, meiwsi_ekpompwn_thermokipioy: meiwsi_ekpompwn_thermokipioy,
        allos_deiktis1: allos_deiktis1, allos_deiktis2: allos_deiktis2, allos_deiktis3:allos_deiktis3, allos_deiktis4: allos_deiktis4, allos_deiktis5: allos_deiktis5 , field9Id: res_data.id } )   
    console.log(req.body)  
    res.send(res_data)
});

module.exports = routes;
